### ISSUE TITLE
Rannked genes with Triku

### ISSUE THREAD

**Issue by SHADJIA** [alexmascension/triku_notebooks#1]
Hello @alexmascension ,

I read your article about your tool Triku. My project is to define minimum number of genes to sequence in case of targeted single cell RNA seq ( rather then WTA). I'm really new for bioinformatics. I usually use R packages and precisely Seurat for my analysis. I'm very bad with python language. 
Can you help me use your tool to obtain ranked genes from my dataset (best 2000 genes for example)?

Thank you in advance for your support.
Regards,
Sha

**Comment by alexmascension** [comment]
Hi Sha.

Do you have an anndata object? If you are working with Seurat you can change one format into the other.

You can also look at the docs front triku, where I explain how to run It.

If you have any doubts, tell me

Best!

**Comment by SHADJIA** [comment]
Hi @alexmascension ,

I converted the Seurat object into anndata and tried your code:

```
import triku as tk

tk.tl.triku(adata)
```
I got error messages.

`ERROR | 2022-07-20 10:27:13,695 - triku.logg - There are genes with no counts. Remove those genes first.You can use sc.pp.filter_genes(adata, min_cells=5).`

Then I tried to filter out genes with no counts as suggested and rerun the code :

```
sc.pp.filter_genes(adata, min_cells=10)
sc.pp.filter_cells(adata, min_genes=50)
tk.tl.triku(adata)
```
But I still get the same error message.

Thanks for your help!
Sha

**Comment by alexmascension** [comment]
Hi @SHADJIA 

Check that your `adata.raw` is empty. If not, you can pass the argument `tk.tl.triku(adata , use_raw=True)` and tell me if it works!

Best

**Comment by SHADJIA** [comment]
I get as output <anndata._core.raw.Raw at 0x1bedbf19850>
I tried your argument but the error persist. I tried to delete the raw data as follow : 
```
del adata.raw
tk.tl.triku(adata)
```
This time, it works but I get another msg : 
```
WARNING | 2022-07-20 14:07:14,777 - triku.logg - X is dense. We will set the matrix to sparse format (csr_matrix).

ERROR | 2022-07-20 14:07:21,153 - triku.logg - The count matrix contains negative values. Triku is supposed to run with positive matrices.
```

**Comment by alexmascension** [comment]
Hi @SHADJIA sorry for the late answer. This error may happen if your normalization pipeline contains some step that yields negative values; or a normalization + log transformation that produces negative values. If so, I'd recommend you not to use that type of method, or to apply a transformation to make negative values neutral or positive.

`sc.pp.filter_genes(adata, min_counts=1)`
`sc.pp.normalize_total(adata)`
`sc.pp.log1p(adata)`

**Comment by SHADJIA** [comment]
Hi @alexmascension ,

Thank you for your reply.
I started using Scanpy to avoid any bias during conversion between Seurat Object to Anndata.
In sum, I should read my data to obtain an Anndata and the use your tool or I should use your tool after every steps of Scanpy. 
actually when I run 
```
sc.pp.filter_genes(adata2, min_cells=10)
sc.pp.filter_cells(adata2, min_genes=50)
tk.tl.triku(adata2)
```
right after the creation of Anndata, I get this error code : 
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
C:\Users\AppData\Local\Temp/ipykernel_22056/614997304.py in <module>
      1 sc.pp.filter_genes(adata2, min_cells=10)
      2 sc.pp.filter_cells(adata2, min_genes=50)
----> 3 tk.tl.triku(adata2)

C:\Users\AppData\Local\R-MINI~1\lib\site-packages\triku\tl\triku.py in triku(object_triku, n_features, use_raw, n_divisions, s, n_windows, min_knn, name, dist_conn, distance_correction, verbose)
    103     try:
    104         if "neighbors" not in object_triku.uns:  # type:ignore
--> 105             raise IndexError(error_ms)
    106     except AttributeError:
    107         raise IndexError(error_ms)

IndexError: Neighbors not found in adata. Run sc.pp.neighbors() first.

```
And when I use your code after all steps, I get the following error : 
```
---------------------------------------------------------------------------
BaseException                             Traceback (most recent call last)
C:\Users\AppData\Local\Temp/ipykernel_22056/1960891115.py in <module>
----> 1 tk.tl.triku(adata2)

C:\Users\AppData\Local\R-MINI~1\lib\site-packages\triku\tl\triku.py in triku(object_triku, n_features, use_raw, n_divisions, s, n_windows, min_knn, name, dist_conn, distance_correction, verbose)
    108 
    109     # Assert that adata.X is sparse (warning to transform) and assert that gene names are unique.
--> 110     arr_counts = get_arr_counts(object_triku, use_raw=use_raw)
    111 
    112     # Get n_divisions if None:

C:\Users\AppData\Local\R-MINI~1\lib\site-packages\triku\utils\_triku_tl_utils.py in get_arr_counts(object_triku, use_raw)
     88 
     89     check_count_mat(arr_counts)
---> 90     check_null_genes(arr_counts)
     91 
     92     return arr_counts

C:\Users\AppData\Local\R-MINI~1\lib\site-packages\triku\utils\_triku_tl_utils.py in check_null_genes(arr_counts)
     38 
     39         triku_logger.error(error_msg)
---> 40         raise BaseException(error_msg)
     41 
     42 

BaseException: There are genes with no counts. Remove those genes first.You can use sc.pp.filter_genes(adata, min_cells=5).
```
Whereas, I have already filtered genes with min_cells = 10.


I'm really sorry for annoying you but your tool is my last hope for getting genes in a ranked order. That's why...

**Comment by alexmascension** [comment]
Hi @SHADJIA,

I don't know why this error occurs if you have already removed your adata.raw from the data file. Try these steps in order to see if they work in that way. 

```
del adata.raw

sc.pp.filter_genes(adata, min_counts=1)
sc.pp.normalize_total(adata)
sc.pp.log1p(adata)

sc.pp.pca(adata,  n_comps=30)
sc.pp.neighbors(adata)
tk.tl.triku(adata, use_raw=False)
```

If not, send me the error throwbacks to see what can I do with that.

Best,

**Comment by SHADJIA** [comment]
Thanks a lot for your help. It works. I could finally get my genes in a ranked order!
